apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduler-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - config.colo-sh.com
      - nodeslo.colo-sh.com
      - scheduling.colo-sh.com
      - coordination.k8s.io
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: colo-scheduler
  namespace: {{ .Values.installation.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: colo-scheduler-as-kube-scheduler
subjects:
  - kind: ServiceAccount
    name: colo-scheduler
    namespace: {{ .Values.installation.namespace }}
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: colo-scheduler-as-volume-scheduler
subjects:
  - kind: ServiceAccount
    name: colo-scheduler
    namespace: {{ .Values.installation.namespace }}
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: colo-scheduler-rolebinding-custom
subjects:
  - kind: ServiceAccount
    name: colo-scheduler
    namespace: {{ .Values.installation.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scheduler-role