kind: Service
apiVersion: v1
metadata:
  name: cololet-svc
  namespace: {{ .Values.installation.namespace }}
  labels:
    app: cololet
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.cololet.port }}
      targetPort: {{ .Values.service.cololet.port }}
  selector:
    app: cololet
  type: {{ .Values.service.cololet.type }}
  sessionAffinity: None