apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-service
  namespace: {{ .Values.installation.namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.service.manager.port }}
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
