apiVersion: v1
data:
  colocation-config: |
    {
      "enable": true,
      "nodeConfigs": [
        {"nodeSelector":{"matchLabels":{"colocation":"on"}}, "metricAggregateDurationSeconds":20}
      ]
    }
  resource-threshold-config: |-
    {
      "clusterStrategy": {
        "enable": false,
        "cpuSuppressThresholdPercent": 65,
        "cpuSuppressPolicy": "cfsQuota",
        "memoryEvictThresholdPercent": 70,
        "memoryEvictLowerPercent": 68,
        "CPUEvictBESatisfactionUpperPercent": 50,
        "CPUEvictBESatisfactionLowerPercent": 30,
        "CPUEvictTimeWindowSeconds": 10,
        "netBELower": "20Mbit",
        "netBEUpper": "1Gbit",
        "netLSRate": "500Mbi",
        "netSuppressBEWindowsPercent": 70,
        "netSuppressLSWindowsPercent": 30,
        "netSuppressStrengthPercent": 25
      }
    }
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: e3594763.colo-sh.com
kind: ConfigMap
metadata:
  name: colo-controller-config
  namespace: {{ .Values.installation.namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: colo-manager
  namespace: {{ .Values.installation.namespace }}