apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: descheduler-role
rules:
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - get
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - scheduling.k8s.io
  resources:
  - "priorityclasses"
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - apps
  resources:
    - '*'
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - apps.kruise.io
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.colo-sh.com
  - nodeslo.colo-sh.com
  - scheduling.colo-sh.com
  - topology.node.k8s.io
  - metrics.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.installation.namespace }}
  name: colo-descheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: descheduler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: descheduler-role
subjects:
  - kind: ServiceAccount
    name: colo-descheduler
    namespace: {{ .Values.installation.namespace }}
