apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: {{ .Values.installation.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: {{ .Values.installation.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - nodeslo.colo-sh.com
    resources:
      - nodemetrics
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nodeslo.colo-sh.com
    resources:
      - nodemetrics/finalizers
    verbs:
      - update
  - apiGroups:
      - nodeslo.colo-sh.com
    resources:
      - nodemetrics/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - nodeslo.colo-sh.com
    resources:
      - nodeslos
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nodeslo.colo-sh.com
    resources:
      - nodeslos/finalizers
    verbs:
      - update
  - apiGroups:
      - nodeslo.colo-sh.com
    resources:
      - nodeslos/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - scheduling.colo-sh.com
    resources:
      - devices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - scheduling.colo-sh.com
    resources:
      - devices/finalizers
    verbs:
      - update
  - apiGroups:
      - scheduling.colo-sh.com
    resources:
      - devices/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - "nodes"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - ""
    resources:
      - "nodes/status"
    verbs:
      - "update"
      - "patch"
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "update"
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "list"


