apiVersion: v1
kind: ConfigMap
metadata:
  name: colo-scheduler-config
  namespace: {{ .Values.installation.namespace }}
data:
  colo-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: colo-scheduler
        plugins:
          preFilter:
            enabled:
            - name: ColocationFit
          filter:
            enabled:
            - name: ColocationFit
          score:
            disabled:
            - name: '*'
            enabled:
            - name: ColocationFit
              weight: 1
          queueSort:
            disabled:
            - name: '*'
            enabled:
            - name: ColocationFit