apiVersion: v1
kind: ServiceAccount
metadata:
  name: colo-scheduler
  namespace: {{ .Values.installation.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: colo-scheduler-as-kube-scheduler
subjects:
  - kind: ServiceAccount
    name: colo-scheduler
    namespace: {{ .Values.installation.namespace }}
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: colo-scheduler-as-volume-scheduler
subjects:
  - kind: ServiceAccount
    name: colo-scheduler
    namespace: {{ .Values.installation.namespace }}
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io