apiVersion: v1
data:
  colocation-config: |
    {
      "enable": true,
      "nodeConfigs": [
        {"nodeSelector":{"matchLabels":{"colocation":"on"}}, "metricAggregateDurationSeconds":20}
      ]
    }
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: e3594763.colo-sh.com
kind: ConfigMap
metadata:
  name: colo-controller-config
  namespace: {{ .Values.installation.namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: colo-manager
  namespace: {{ .Values.installation.namespace }}