apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-config
  namespace: {{ .Values.installation.namespace }}
data:
  colo-descheduler-config: |
    apiVersion: descheduler/v1alpha2
    kind: DeschedulerConfiguration
    enableContentionProfiling: true
    enableProfiling: true
    healthzBindAddress: 0.0.0.0:10251
    metricsBindAddress: 0.0.0.0:10251
    leaderElection:
      resourceLock: leases
      resourceName: colo-descheduler
      resourceNamespace: {{ .Values.installation.namespace }}
    deschedulingInterval: 10s
    dryRun: false
    profiles:
      - name: colo-descheduler
        plugins:
          deschedule:
            disabled:
              - name: "*"
          evict:
            disabled:
              - name: "*"
            enabled:
              - name: MigrationController
          balance:
            enabled:
              - name: LowNodeLoad
        pluginConfig:
          - name: MigrationController
            args:
              apiVersion: descheduler/v1alpha2
              kind: MigrationControllerArgs
              evictionPolicy: Eviction
              namespaces:
                exclude:
                  - "kube-system"
                  - "colo-system"
                  - "istio-system"
                  - "adele-system"
                  - "tidb"
                  - "psr"
                  - "snail"
                  - "drangonstone-v2-system"
                  - "turtle"
                  - "lord"
                  - "zeal"
                  - "cmdb"
                  - "observability"
                  - "kafka"
                  - "kingshard"
              evictQPS: "10"
              evictBurst: 1
          - name: LowNodeLoad
            args:
              apiVersion: descheduler/v1alpha2
              kind: LowNodeLoadArgs
              evictableNamespaces:
                exclude:
                  - "kube-system"
                  - "colo-system"
                  - "istio-system"
                  - "adele-system"
                  - "tidb"
                  - "psr"
                  - "snail"
                  - "drangonstone-v2-system"
                  - "turtle"
                  - "lord"
                  - "zeal"
                  - "cmdb"
                  - "observability"
                  - "kafka"
                  - "kingshard"
              lowThresholds:
                cpu: 30
                memory: 30
              highThresholds:
                cpu: 50
                memory: 50
