apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pod-webhook
  name: pod-webhook
  namespace: colo-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: pod-webhook-server
status:
  loadBalancer: {}
